spring:
  profiles:
    #本机环境:local 开发环境:dev 测试环境:test 生产环境:prod
    active: local

logging.level.com.iwhalecloud.retail.oms.mapper: debug

mybatis-plus:
  mapperLocations: classpath:oms/mapper/*.xml,oms/mapper/mysql/*.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#验证码有效时间
effInterval: 300000