project:
  name: 测试环境

server:
  port: 8328

spring:
  dubbo:
    application:
      name: report-provider
    registry:
      address: zookeeper://10.45.47.87:2285
    protocol:
      name: dubbo
      port: 27901
    scan: com.iwhalecloud.retail

jmx:
  enabled: false

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.45.47.88:3306/nretail
  username: nretail
  password: nretail
