spring:
  profiles:
    active: local

logging.level.com.iwhalecloud.retail.warehouse.mapper: debug

mybatis-plus:
  mapperLocations: classpath:warehouse/mapper/*.xml,warehouse/mapper/mysql/*.xml

#用来后去主键生成策略
#TelDB
#Oracle
#MySql
db-type: TelDB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

