project:
  name: 本机环境

server:
  port: 8025

spring:
  dubbo:
    application:
      name: warehouse-provider
    registry:
#      address: zookeeper://10.45.47.87:2285
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20888
    scan: com.iwhalecloud.retail

jmx:
  enabled: false

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.45.46.67:8866/YHJDB?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
  username: szxtest
  password: szxtest.2019

# 分布式文件系统FDFS配置
fdfs:
  showUrl: https://gy.ztesoft.com/
#能开配置
zop:
  secret: ODA1NzM5Zjg1ZDVmNDBiNGVjYzVkNzVmOGJmZTRlYmM=
  url: http://134.176.102.33:8081/api
  timeout: 50000
