project:
  name: 开发环境

server:
  port: 8081

spring:
  dubbo:
    application:
      name: rights-provider
    registry:
      address: zookeeper://10.45.47.90:2121
    protocol:
      name: dubbo
      port: 20881
    scan: com.iwhalecloud.retail

jmx:
  enabled: false
  
spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.45.47.88:3306/rights
  username: rights
  password: rights

