server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenmget/spring-cloud-demo/tree/release/spring-cloud-demo/spring-cloud-config/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 502298798@qq.com                            # git仓库的账号
          password: Chenmin2015                                 # git仓库的密码