project:
  name: 本机环境
  
server:
  port: 8325

spring.dubbo:
    application:
      name: wf-provider
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.iwhalecloud.retail

spring.redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
    cluster:
      nodes: 10.45.47.129:7021,10.45.47.129:7022,10.45.47.129:7023,10.45.47.129:7024,10.45.47.129:7025,10.45.47.129:7026
      timeout: 10000
      max-redirects: 3
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
    pool:
      max-active: 600
      max-idle: 300
      max-wait: 1000
      min-idle: 5
    password:

logging.level.com.iwhalecloud.retail.workflow.mapper: debug
 
#spring.datasource:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://10.45.47.88:3306/nretail_b2b?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#  username: oms
#  password: oms

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.45.46.67:8866/YHJDB?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
  username: szxtest
  password: szxtest.2019