project:
  name: 本机环境
  
server:
  port: 8325

spring.dubbo:
    application:
      name: wf-provider
    registry:
      address: zookeeper://localhost:2181
      username:
      password:
    protocol:
      name: dubbo
      port: 20880
    scan: com.iwhalecloud.retail
    consumer:
      check: false
      timeout: 5000
      retries: 0
      filter: sourceFromConsumerfilter,sourceFromProviderfilter

spring.redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
    cluster:
      nodes: 10.45.47.129:7021,10.45.47.129:7022,10.45.47.129:7023,10.45.47.129:7024,10.45.47.129:7025,10.45.47.129:7026
      timeout: 10000
      max-redirects: 3
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
    pool:
      max-active: 600
      max-idle: 300
      max-wait: 1000
      min-idle: 5
#    password:

logging.level.com.iwhalecloud.retail.workflow.mapper: debug
 
#spring.datasource:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://10.45.47.88:3306/nretail_b2b?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#  username: oms
#  password: oms

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
  username: root
  #password: szxtest.2019
  password: ZNmIRY6McMPtPusgP40HmKfy8AqHRDe/mtmrVgyMtNaOMmV86vPN2AtRZkOCppuEttR8oyOfSd5ZOOo/++imKw==

  druid:
    #2.连接池配置
    #初始化连接池的连接数量 大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 5
    keep-alive: true
    removeAbandoned: true
    #配置获取连接等待超时的时间.
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 30000
    validation-query: SELECT 1
    test-on-borrow: true
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filter:
      stat:
        merge-sql: true
        slow-sql-millis: 5000
    #3.基础监控配置
    
    web-stat-filter:
      enabled: true
      url-pattern: /*
      #设置不统计哪些URL
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      session-stat-enable: true
      session-stat-max-count: 100
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      reset-enable: true
      #设置监控页面的登录名和密码
      login-username: admin
      login-password: c481af4a-df94-3413-7e22-24daf5b3a9bb
      allow: 127.0.0.1
    filters: config,stat,log4j,wall
    #设置public key
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMJjq0F7UAdcJZbgqvv/Gciy0omnugNn+nHkd0vw6scOeoZu+KASJr8G6lmy1FJ1S5wc6yj0YSUH1FwOxo/NwLcCAwEAAQ==
