project:
  name: 开发环境

server:
  port: 8082

spring:
  dubbo:
    application:
      name: order-consumer
    registry:
      address: zookeeper://10.45.47.90:2121
    #      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.iwhalecloud.retail
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    clusterNodes: 10.45.47.129:7021,10.45.47.129:7022,10.45.47.129:7023,10.45.47.129:7024,10.45.47.129:7025,10.45.47.129:7026
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
  pool:
    max-active: 600
    max-idle: 300
    max-wait: 1000
    min-idle: 5
  http:
      multipart:
        enabled: true
        max-file-size: 5MB
        max-request-size: 10MB

wechat:
  mp:
    appId: wx649eb094afb490f5
    secret: a7518177097a778bcce59f09832142da
    token: iwhalecloud
    aesKey: 1CLJdwSqEoIS9Ym7HucEGdgsTbZ9m5hKdCQTEUAKKih
    notifyServer: https://gy.ztesoft.com

pay:
  key: 113309875849
  busi_channel: channel
  account_id: acount
  pay_url: http://134.176.102.33:8081/api/rest
  return_url: http://127.0.0.1:8081/api/pay/notifyUrl
  notify_url: http://127.0.0.1:8081/api/pay/notifyUrl

# 分布式文件系统FDFS配置
fdfs:
  showUrl: https://gy.ztesoft.com/
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  thumbImage: #缩略图生成参数，可选
      width: 150
      height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port :NRetail/NRetail
    - 10.45.47.87:22133
    - 10.45.47.90:22133
    - 10.45.47.89:22133
  pool:
    jmx-enabled: false
  suffix:  #配置允许附件上传的后缀
    allowUpload: bmp,jpg,jpeg,png,tif,gif,pcx,tga,exif,fpx,svg,psd,cdr,pcd,dxf,ufo,eps,ai,raw,WMF,webp,avi,wmv,mpeg,mp4,mov,mkv,flv,f4v,m4v,rmvb,rm,3gp,dat,ts,mts,vob,xls,xlsx

#能开参数配置
zop:
  appId: thisisappid
  appSecret: thisisappsecret
  url: thisisurl
  timeout: 3000

#jwt
jwt:
  secret: A5-!^!.X3K
  #  token有效时间（分钟）
  expiresAt: 120

#logging.path: ../
#logging.file: **.log
logging.level.root: WARN
# 指定包的日志设置为warn
logging.level.com.iwhalecloud.retail: INFO
logging.level.org.springframework.boot.context.embedded: INFO
logging.pattern.console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
logging.pattern.file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"