project:
  name: 本机环境
  
server:
  port: 8026

spring.dubbo:
    application:
      name: promo-provider
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20886
    scan: com.iwhalecloud.retail
  
logging.level.com.iwhalecloud.retail.promo.mapper: debug
 
#spring.datasource:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://10.45.47.88:3306/nretail_b2b?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#  username: oms
#  password: oms

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.45.46.67:8866/YHJDB?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
  username: szxtest
  password: szxtest.2019