spring:
  profiles:
    active: local

logging.level.com.iwhalecloud.retail.system.mapper: debug

mybatis-plus:
  mapperLocations: classpath:system/mapper/*.xml,system/mapper/mysql/*.xml
#  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 3
  keyGenerator: com.iwhalecloud.retail.system.incrementer.TelDbKeyGenerator

#用来后去主键生成策略
#TelDB
#Oracle
#MySql
db-type: TelDB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#验证码有效时间
effInterval: 300000