project:
  name: 本机环境

server:
  port: 8084

spring:
  dubbo:
    application:
      name: system-provider
    registry:
#      address: zookeeper://10.45.47.87:2285
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20884
    scan: com.iwhalecloud.retail

  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
    cluster:
      nodes: 10.45.47.129:7021,10.45.47.129:7022,10.45.47.129:7023,10.45.47.129:7024,10.45.47.129:7025,10.45.47.129:7026
      timeout: 10000
      max-redirects: 3
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
    pool:
      max-active: 600
      max-idle: 300
      max-wait: 1000
      min-idle: 5
    password:

  #i18n国际化配置
  messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: i18n/system
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    cache-seconds: 3600
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8
jmx:
  enabled: false

#spring.datasource:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://10.45.47.88:3306/nretail_b2b
#  username: oms
#  password: oms

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.45.46.67:8866/YHJDB?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
  username: szxtest
  password: szxtest.2019

# 分布式文件系统FDFS配置
fdfs:
  showUrl: https://gy.ztesoft.com/

