logging.level.com.iwhalecloud.retail.goods.mapper: debug

mybatis-plus:
  mapperLocations: classpath:goods/mapper/*.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
project:
  name: 测试环境

server:
  port: 8323

spring:
  dubbo:
    application:
      name: goods-provider
    registry:
      address: zookeeper://10.45.47.87:2281
    protocol:
      name: dubbo
      port: 27889
    scan: com.iwhalecloud.retail
  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
    cluster:
      nodes: 10.45.47.129:7021,10.45.47.129:7022,10.45.47.129:7023,10.45.47.129:7024,10.45.47.129:7025,10.45.47.129:7026
      timeout: 10000
      max-redirects: 3
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
    pool:
      max-active: 600
      max-idle: 300
      max-wait: 1000
      min-idle: 5
    password:

jmx:
  enabled: false

#spring.datasource:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://10.45.47.88:3306/nretail
#  username: nretail
#  password: nretail

# 分布式文件系统FDFS配置
fdfs:
  showUrl: https://gy.ztesoft.com/