mybatis-plus:
  mapperLocations: classpath:order/mapper/*.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring.mybatis.mappers: classpath:order/mapper/*.xml
spring.mybatis.scan.package: com.iwhalecloud.retail.order.mapper
project:
  name: 测试环境
  
server:
  port: 8324

spring.dubbo:
    application:
      name: order-provider
    registry:
      address: zookeeper://10.45.47.87:2281
    protocol:
      name: dubbo
      port: 27083
    scan: com.iwhalecloud.retail
  
logging.level.com.iwhalecloud.retail.order.mapper: debug

fdfs.show.url: https://gy.ztesoft.com/
 
#spring.datasource:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://10.45.47.88:3306/nretail
#  username: nretail
#  password: nretail

#spring.datasource:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://10.45.46.67:8866/nretail_b2b?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#  username: szxtest
#  password: szxtest.2019
