# FROM 10.45.80.1/public/openjdk_java8_cloud_ci:latest
FROM 10.45.80.1/public/centos7-java-base:openjdk1.8.0.151

MAINTAINER obed


RUN mkdir /opt/ZSMART_HOME  \
    && mkdir /opt/ZSMART_HOME/config    \
    && mkdir /opt/ZSMART_HOME/webapps   \
    && mkdir /opt/ZSMART_HOME/logs  \
#    && echo 'APP=("webapp")\nwebapp=("nohup java -jar -Dspring.profiles.active=system /opt/ZSMART_HOME/webapps/system-service.jar --spring.config.location=/opt/ZSMART_HOME/config/ > /opt/ZSMART_HOME/logs/system.log&"\n"webapp")' > /root/docker-app.def   \
    && echo 'APP=( "webapp" )'>> /root/docker-app.def  \
    && echo 'webapp=(' >> /root/docker-app.def \
    && echo '"nohup java -jar -Dspring.profiles.active=system /opt/ZSMART_HOME/webapps/system-service.jar --spring.config.location=/opt/ZSMART_HOME/config/ > /opt/ZSMART_HOME/logs/system.log&"' >> /root/docker-app.def    \ 
    && echo '"webapp"' >> /root/docker-app.def  \
    && echo ")" >> /root/docker-app.def \
    && chmod +x /root/docker-app.def    \
	&& echo "CLASSPATH=$CLASSPATH:/opt/ZSMART_HOME:/opt/ZSMART_HOME/config" > /opt/ZSMART_HOME/setenv.sh  \
    && echo "nohup java -jar -Dspring.profiles.active=system /opt/ZSMART_HOME/webapps/system-service.jar --spring.config.location=/opt/ZSMART_HOME/config/ > /opt/ZSMART_HOME/logs/system.log& " > /opt/ZSMART_HOME/start.sh \
    && chmod +x /opt/ZSMART_HOME/* 

COPY system/system-service-boot/target/system-service.jar /opt/ZSMART_HOME/webapps/system-service.jar

# RUN nohup java -jar -Dspring.profiles.active=system /opt/ZSMART_HOME/webapps/system-service.jar --spring.config.location=/opt/ZSMART_HOME/config/ > /opt/ZSMART_HOME/logs/system.log& 
    
EXPOSE 8080

VOLUME [ "/opt/ZSMART_HOME/logs" ]
LABEL zcm.logs.myapp="/opt/ZSMART_HOME/logs/*.log"
LABEL zcm.logs.myapp.tags="project=kp"
ENV APP_NAME=b2b_system

ENV PINPOINT_TRACE=on
ENV ZSMART_HOME=/opt/ZSMART_HOME
ENV PATH $PATH:$ZSMART_HOME

ENV JAVA_OPTS="$JAVA_OPTS -d64 -XX:+HeapDumpOnOutOfMemoryError -Xms1024m -Xmx2048m -XX:PermSize=128M -XX:MaxPermSize=256m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
ENV HOUND_HOME=/opt/ZSMART_HOME
ENV z_app=b2b_system

CMD ["start"]
# CMD /opt/ZSMART_HOME/start.sh

