project:
  name: 本机环境
  
server:
  port: 8024

spring.dubbo:
    application:
      name: order2b-provider
    registry:
 #     address: zookeeper://10.45.47.87:2285 10.45.46.238:8121
      address: zookeeper://localhost:2181
#      address: zookeeper://172.21.72.75:8121
    protocol:
      name: dubbo
      port: 20882
    scan: com.iwhalecloud.retail
  
logging.level.com.iwhalecloud.retail.order2b.mapper: debug

fdfs.show.url: https://gy.ztesoft.com/
 
#spring.datasource:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://10.45.47.88:3306/nretail_b2b
#  username: oms
#  password: oms

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.45.46.67:8866/YHJDB_TEST?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
  username: szxtest
  #password: szxtest.2019
  password: kw0KpgWfOpAVqO4sdMTlLIcXrbbZOIXl4gwhUZqqNehmasEh/58907TPY7kguZ91Ke7rGLUVEkX5YpOBemm18g==

  druid:
    #2.连接池配置
    #初始化连接池的连接数量 大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 50
    #配置获取连接等待超时的时间.
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 30000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filter:
      stat:
        merge-sql: true
        slow-sql-millis: 5000
    #3.基础监控配置
    web-stat-filter:
      enabled: true
      url-pattern: /*
      #设置不统计哪些URL
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      session-stat-enable: true
      session-stat-max-count: 100
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      reset-enable: true
      #设置监控页面的登录名和密码
      login-username: admin
      login-password: c481af4a-df94-3413-7e22-24daf5b3a9bb
      allow: 127.0.0.1
    filters: config,stat,wall,log4j
    #设置public key
    connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJptiLaauFuYuwkmQ2S0NSsvjdka34BLnbG5zFcuRqFi7RJowXs7P/dSmQWmlrx5RekyriyBUzgAgSbTFt1NpMsCAwEAAQ==


  #i18n国际化配置
spring.messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: i18n/order2b
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    cache-seconds: 3600
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8

#翼支付企业支付配置文件及相关配置参数
pay:
  certificateFile: classpath:pay/bestpay.properties
  payAuthUrl: http://116.228.151.160:18183/preAuthorizationApply
  payConfirmUrl: http://116.228.151.160:18183/preAuthorizationConfirm
  payCancelUrl: http://116.228.151.160:18183/preAuthorizationCancel
  merchantCertificatePath: classpath:pay/cert/server.jks
  merchantCertificatePwd: 123456
  bestpayCertificatePath: MIIEdTCCA12gAwIBAgIQeOYX576OwdBzGHctPw6PSTANBgkqhkiG9w0BAQUFADBvMQswCQYDVQQGEwJDTjEkMCIGA1UEChMbTkVUQ0EgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRkwFwYDVQQLExBTZXJ2ZXIgQ2xhc3NBIENBMR8wHQYDVQQDExZORVRDQSBTZXJ2ZXIgQ2xhc3NBIENBMB4XDTEyMDMzMTE2MDAwMFoXDTE1MDQwMTE1NTk1OVowZzELMAkGA1UEBhMCQ04xEjAQBgNVBAgTCUd1YW5nZG9uZzErMCkGA1UECh4iZw1SoVZoi8FOZm1Li9UAMgAwADEAMgAwADQAMAAxAC0ANDEXMBUGA1UEAxMOdGVzdDIwMTIwNDAxLTQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDYWtX4YTIYgmXAC6l2E//GQ1SjymJyPGNoDav+MJtUpXzcdub4yfKiLa6HWzzKUl9YyokwGtMUu020+8yy6BUNlmElcgrdqmZyej8fjlzjCw8BLwrxxKcbR9HZ8OEu1VSpy1w/KYpCEqT1gi4T3LP+Ug2SVbIXuFMsPSwywwVtl8mMcXQ3PqjD72IK+cOnWCimFk590uLlnyy6/z3vMa+XbjUG3haoCS8WLsJNufbs8HccTE6FYctCDNuSwhD7YOqKlMoMFnFnEN6wvZ57GS3NM1dd2sSqE4Ma8gE75w3VdOuoKsjnWfrGkbhkUmBiVuACt+/Aw3m8mngx33qyKjURAgMBAAGjggETMIIBDzAfBgNVHSMEGDAWgBS680oFJOb4JMjmV9p4jQxZ5ENkyjAdBgNVHQ4EFgQUKl+CBlrjAlL1DUAJs4M2QqAq2xMwVwYDVR0gBFAwTjBMBgorBgEEAYGSSAEKMD4wPAYIKwYBBQUHAgEWMGh0dHA6Ly93d3cuY25jYS5uZXQvY3Mva25vd2xlZGdlL3doaXRlcGFwZXIvY3BzLzAZBgNVHREEEjAQgg50ZXN0MjAxMjA0MDEtNDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIEsDA7BgNVHR8ENDAyMDCgLqAshipodHRwOi8vY2xhc3NhY2ExLmNuY2EubmV0L2NybC9TZXJ2ZXJDQS5jcmwwDQYJKoZIhvcNAQEFBQADggEBAJ4QaFZjJ12Ayvyy0JyNZQ9eeNmCAUt4+aZY6IT/FDfm9HFB7jkVXxDY+eUTHc/cu4fDIidCNz+CTGlRoiVWJkDyQfmBpcXJE1OPJSHzMXXDgGfxstqZDkDJ+NAAX8TSunnd4/y/BjO/uoOxytVmetxWOxt4s6IhITzZS2y7Kntoghd+6IVK20VFS9mhqUL/YiRI4RU+TrjU8zm7+QSTpqfXfOwn1x8Eol+Pwu9+ZdMNLCA8MbbtmMKz/vbxMwBoFv9kedH0ui7d5AQiNGQHxp0IGYc1L48KpLE8bDeyjGNU+VjI/gmzxYM6bwOqLpoENnWm7M3NLhtIDj98Z4Wftrc=
  iv: 1234567892546398
  platCode: "0020000000050033"
  platformCode: "0020000000050033"
  type: bestpay
  ipStr: 127.0.0.1

#订单数据推送FTP文件路径
ftp:
  order:
    dataPathAgo: /tmp/order/ago
    dataPathMid: /tmp/order/mid

#能开配置
zop:
  secret: ODA1NzM5Zjg1ZDVmNDBiNGVjYzVkNzVmOGJmZTRlYmM=
  url: http://134.176.102.33:8081/api/rest
  timeout: 50000
  #翼支付测试地址
  payAuthMethod: ord.operbalance.preAuthApply
  payConfirmMethod: ord.operbalance.preAuthConfirm
  payCancelMethod: ord.operbalance.preAuthCancel