FROM 10.45.80.1/public/centos7_java8_tomcat8_base:8.0.35

RUN mkdir /opt/ZSMART_HOME  \
    && mkdir /opt/ZSMART_HOME/config    \
    && mkdir /opt/ZSMART_HOME/webapps   \
    && mkdir /opt/ZSMART_HOME/logs  \
    && mkdir /usr/tomcat/tomcat8.0/webserver/webapps/ShelfManager   \
    && echo 'APP=( "tomcat" )'>> /root/docker-app.def  \
    && echo 'tomcat=(' >> /root/docker-app.def \
    && echo '"/usr/tomcat/tomcat8.0/webserver/bin/catalina.sh run"' >> /root/docker-app.def    \
    && echo '"tomcat"' >> /root/docker-app.def  \
    && echo ")" >> /root/docker-app.def \
    && chmod +x /root/docker-app.def    \
  && echo "CLASSPATH=$CLASSPATH:/opt/ZSMART_HOME:/opt/ZSMART_HOME/config" > /usr/tomcat/tomcat8.0/webserver/bin/setenv.sh  \
    && chmod +x /usr/tomcat/tomcat8.0/webserver/bin/*.sh   \
    && chmod +x /opt/ZSMART_HOME/*

COPY java/web/retail-web-boot/target/retail-web.war /usr/tomcat/tomcat8.0/webserver/webapps/retail-web.jar
COPY js/build/* /usr/tomcat/tomcat8.0/webserver/webapps/ShelfManager/*

EXPOSE 8080

VOLUME [ "/usr/tomcat/tomcat8.0/webserver/logs" ]
LABEL zcm.logs.myapp="/usr/tomcat/tomcat8.0/webserver/logs/*.log"
LABEL zcm.logs.myapp.tags="project=kp"
ENV APP_NAME=b2c_web
ENV HOME = /usr/tomcat/tomcat8.0/webserver/logs

ENV PINPOINT_TRACE=on
ENV ZSMART_HOME=/opt/ZSMART_HOME
ENV PATH $PATH:$ZSMART_HOME

ENV JAVA_OPTS="$JAVA_OPTS -d64 -XX:+HeapDumpOnOutOfMemoryError -Xms1024m -Xmx2048m -XX:PermSize=128M -XX:MaxPermSize=256m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
ENV HOUND_HOME=/opt/ZSMART_HOME
ENV z_app=b2c_web

CMD ["start"]
